# Generated by Django 4.2.23 on 2025-06-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avg_calc", "0006_recentactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
