# Generated by Django 5.0.7 on 2024-08-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avg_calc", "0006_recentactivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkTimeCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_avg", models.FloatField()),
                ("leave_days", models.IntegerField()),
                ("required_daily_hours", models.FloatField(blank=True, null=True)),
                ("remaining_required_hours", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
